name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BuildConfig: 'Release'
  SolutionFile: SnipsSolution/SnipsSolution.sln
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SolutionFile }}
    - name: Build
      run: dotnet build ${{ env.SolutionFile }}          
            --no-restore
            --configuration ${{ env.BuildConfig }}                       
          
    - name: Test
      run: dotnet test ${{ env.SolutionFile }} --no-build --configuration ${{ env.BuildConfig }} --verbosity normal 
